CC      = gcc
CFLAGS  = -Wall -Wextra -std=c99 -O3
SRC     = $(wildcard src/*.c)
OBJ     = $(SRC:.c=.o)
INC     = -Iinclude

pendulo: $(OBJ)
	$(CC) $(CFLAGS) $^ -lm -o $@

test: pendulo
	./tests/run_tests.sh
