import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/θωxy_adaptive.csv')
plt.figure(figsize=(6,6))
plt.plot(df['x'], df['y'], linewidth=1)
plt.xlabel('x (m)')
plt.ylabel('y (m)')
plt.title('Trajetória do Pêndulo')
plt.axis('equal')
plt.grid(True)
plt.show()

df = pd.read_csv('data/θωxy_adaptive.csv')
plt.figure(figsize=(6,6))
plt.plot(df['t'], df['theta'], linewidth=1)
plt.xlabel('Time (s)')
plt.ylabel('Theta (rad)')
plt.title('T x Theta do Pêndulo')
plt.axis('equal')
plt.grid(True)
plt.show()

df = pd.read_csv('data/θωxy_fixed.csv')
plt.figure(figsize=(6,6))
plt.plot(df['x'], df['y'], linewidth=1)
plt.xlabel('x (m)')
plt.ylabel('y (m)')
plt.title('Trajetória do Pêndulo')
plt.axis('equal')
plt.grid(True)
plt.show()

df = pd.read_csv('data/θωxy_fixed.csv')
plt.figure(figsize=(6,6))
plt.plot(df['t'], df['theta'], linewidth=1)
plt.xlabel('Time (s)')
plt.ylabel('Theta (rad)')
plt.title('T x Theta do Pêndulo')
plt.axis('equal')
plt.grid(True)
plt.show()